
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html:cached
            - composer_cache:/composer/cache
            - vendor:/var/www/html/vendor
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        ports:
            - "9000:9000"
            - "49769:49769"  # Updated Xdebug port
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            XDEBUG_MODE: "debug"
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=49769"
            COMPOSER_PROCESS_TIMEOUT: 2000
            COMPOSER_MEMORY_LIMIT: -1
        networks:
            - laravel-network

    nginx:
        image: nginx:1.26-alpine
        container_name: task-api-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel-network

    db:
        image: mysql:8.0
        container_name: task-api-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    dbdata:
    composer_cache:
    vendor:
