
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - task-api-network

  nginx:
    image: nginx:1.26-alpine
    container_name: task-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - task-api-network

  db:
    image: mysql:8.0
    container_name: task-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - task-api-network

networks:
  task-api-network:
    driver: bridge

volumes:
  dbdata:
